// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaIu_W1iBcb1FZ6ME1Mp8iMA5RvQnBsrQ',
    appId: '1:768364411855:web:932fd2631264a6462a70ba',
    messagingSenderId: '768364411855',
    projectId: 'platzitripsflutter-3c365',
    authDomain: 'platzitripsflutter-3c365.firebaseapp.com',
    databaseURL: 'https://platzitripsflutter-3c365-default-rtdb.firebaseio.com',
    storageBucket: 'platzitripsflutter-3c365.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkvLug3Xr5GdDN8BWfdR8mh7IywA818M',
    appId: '1:768364411855:android:88b5e368a52e2d5a2a70ba',
    messagingSenderId: '768364411855',
    projectId: 'platzitripsflutter-3c365',
    databaseURL: 'https://platzitripsflutter-3c365-default-rtdb.firebaseio.com',
    storageBucket: 'platzitripsflutter-3c365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkYRXF3OdDM149ONG-s8YHYfbgmHLfok4',
    appId: '1:768364411855:ios:ba8406f70aa602c52a70ba',
    messagingSenderId: '768364411855',
    projectId: 'platzitripsflutter-3c365',
    databaseURL: 'https://platzitripsflutter-3c365-default-rtdb.firebaseio.com',
    storageBucket: 'platzitripsflutter-3c365.appspot.com',
    androidClientId: '768364411855-7dvbek540vphlhtapjdteqg5hcrnkhl6.apps.googleusercontent.com',
    iosClientId: '768364411855-2l0sno9lccj3e0u17jmp9qfcpqtariun.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
